version: '3.5'
services:
  db:
    image: mariadb
    ports:
      - '18806:3306'
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=325058560
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: project1
